### ISSUE TITLE
Can this method only be used for image style conversion between day and night?

### ISSUE THREAD

**Issue by mengjingyouling** [cv-rits/ManiFest#2]
Can this method only be used for image style conversion between day and night?Can it be used to generate fog scenes?

**Comment by fabvio** [comment]
Hello and thanks for your interest.
Of course not, we offer a large range of transformations, if you read the paper you will find weather conditions such as fog but also more extreme generations such as volcanos, auroras, etc. We also provide the checkpoints for fog/twilight generation.

**Comment by mengjingyouling** [comment]
Very solid work.
 I will carefully read your paper and try to introduce it into our work.

**Comment by fabvio** [comment]
Thanks!
