### ISSUE TITLE
Ask for the Supplemenntary Materials of this paper

### ISSUE THREAD

**Issue by ZHANG-YSen** [cv-rits/ManiFest#6]
Hello, sorry for disturbing you!

I saw some details in the article that will be presented in the supplementary materials, but I did not find them on the internet. Therefore, I would like to request that you provide the supplementary materials for this article.

I‘m much obliged to you for helping me.

**Comment by fabvio** [comment]
Hello and thanks for your interest! You can find the supplementary here:
https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136770443-supp.zip

**Comment by ZHANG-YSen** [comment]
I have received it, thank you very much!



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月13日(星期四) 下午5:36
收件人: "astra-vision/ManiFest";
抄送: "Author";
主题: Re: [astra-vision/ManiFest] Ask for the Supplemenntary Materials of this paper (Issue #6)





 
Hello and thanks for your interest! You can find the supplementary here:
 https://www.ecva.net/papers/eccv_2022/papers_ECCV/papers/136770443-supp.zip
 
&mdash;
